/** Minimal valid raw `.env` map for config tests: strings in, as `loadEnv` reads them from disk. */
export const RAW_ENV_BASE: Readonly<Record<string, string>> = {
  APP_NAME: "Bun ERP Template",
  APP_ENV: "development",
  APP_PORT: "3000",
  APP_RELEASE: "test",
  APP_TIMEZONE: "UTC",
  LOG_DRIVER: "console",
  LOG_LEVEL: "info",
  LOG_PATH: "/dev/stdout",
  LOG_RETENTION_DAYS: "14",
  LOG_MAX_SIZE_MB: "100",
  STORAGE_DRIVER: "memory",
  APP_URL: "http://localhost:3000",
  DATABASE_URL: "postgresql://user:pass@localhost:5432/erp",
  BETTER_AUTH_URL: "http://localhost:3000",
  BETTER_AUTH_SECRET: "x".repeat(40),
  MAIL_FROM_ADDRESS: "no-reply@example.test",
  MAIL_FROM_NAME: "Bun ERP Template",
  MAIL_DRIVER: "log",
};
