import { resolve } from "node:path";
import { isTemplateRepo } from "../gates/lifecycle.ts";
import { installedFeatureNames } from "./feature-catalog.ts";
import { fileIndex } from "./file-index.ts";
import { installedPackageNames } from "./package-catalog.ts";

/**
 * Guidelines aggregation for agents. The block in AGENTS.md is generated, never hand-edited:
 * `features:install`, `packages:install` and `ai:update` refresh it from the installed catalog,
 * so the guide paths stay correct without anyone maintaining a second list.
 */

export const GUIDELINES_START = "<!-- guidelines:start -->";
export const GUIDELINES_END = "<!-- guidelines:end -->";
export const GOAL_START = "<!-- goal:start -->";
export const GOAL_END = "<!-- goal:end -->";
export const PLATFORM_START = "<!-- platform-limits:start -->";
export const PLATFORM_END = "<!-- platform-limits:end -->";
export const AGENTS_FILE = "AGENTS.md";

export type GuidelinesStatus = "updated" | "unchanged" | "missing";

/** Replaces the marked block in place; a source without both markers is left untouched. */
export function applyGuidelinesBlock(
  source: string,
  block: string,
  markers: { start: string; end: string } = { start: GUIDELINES_START, end: GUIDELINES_END },
): { source: string; status: GuidelinesStatus } {
  const start = source.indexOf(markers.start);
  const end = source.indexOf(markers.end);
  if (start < 0 || end < start) return { source, status: "missing" };
  const replaced = `${source.slice(0, start)}${block}${source.slice(end + markers.end.length)}`;
  return { source: replaced, status: replaced === source ? "unchanged" : "updated" };
}

async function installedAppEntries(root: string, templateMode: boolean): Promise<string[]> {
  const names = (await fileIndex(root).files("apps/*/package.json"))
    .map((file) => file.split("/")[1])
    .filter((name): name is string => Boolean(name))
    .sort();
  const entries: string[] = [];
  for (const name of names) {
    const manifest = (await Bun.file(resolve(root, "apps", name, "package.json")).json()) as { name?: string };
    const appReadme = `apps/${name}/README.md`;
    // A project's apps are documented by the project docs; only the template points at its catalog.
    const fallback = templateMode ? "templates/apps/README.md" : "docs/development.md";
    const guide = (await Bun.file(resolve(root, appReadme)).exists()) ? appReadme : fallback;
    entries.push(`\`${name}\` (\`${manifest.name ?? name}\`) — guide: \`${guide}\``);
  }
  return entries;
}

async function featureEntries(root: string): Promise<string[]> {
  const names = await installedFeatureNames(root);
  const entries: string[] = [];
  for (const name of names) {
    const readme = `templates/features/${name}/README.md`;
    const guide = (await Bun.file(resolve(root, readme)).exists()) ? readme : "templates/features/README.md";
    entries.push(`\`${name}\` — guide: \`${guide}\``);
  }
  return entries;
}

/** Deterministic, sorted, and small: one line per catalog area, guide paths included. */
export async function renderGuidelinesBlock(root: string): Promise<string> {
  const templateMode = await isTemplateRepo(root);
  const apps = await installedAppEntries(root, templateMode);
  const packages = (await installedPackageNames(root)).map((name) => `\`${name}\` (\`packages/${name}/llms.txt\`)`);
  const features = await featureEntries(root);
  const lines = [
    GUIDELINES_START,
    "Generated by `bun erp ai:update`; refresh it after installing apps, packages or features.",
    apps.length > 0
      ? `- Apps: ${apps.join("; ")}`
      : templateMode
        ? "- Apps: none installed — catalog guide: `templates/apps/README.md`"
        : "- Apps: none installed — run `bun erp init`; guide: `docs/development.md`",
    packages.length > 0
      ? `- Packages: ${packages.join("; ")}`
      : "- Packages: none installed — catalog: `templates/packages`",
    features.length > 0
      ? `- Features: ${features.join("; ")}; catalog guide: \`templates/features/README.md\``
      : "- Features: none installed — catalog guide: `templates/features/README.md`",
    GUIDELINES_END,
  ];
  return lines.join("\n");
}

/** Goal section body: one codebase, two production targets. */
export function renderGoalBlock(): string {
  return [
    GOAL_START,
    "Build internal applications as a semi-monolith that can split into services later, with",
    "Laravel-level productivity for agents and humans, on one codebase that runs on a plain VPS",
    "(Bun/Docker, the default production target) and on Cloudflare Workers (Free or Paid):",
    "",
    "- **Semi-monolith, microservice-ready.** Feature boundaries are explicit and a feature owns its",
    "  routes, jobs and tables, so extraction is a move, not a rewrite (docs/architecture.md,",
    '  "Splitting a feature into a service").',
    "- **Laravel-level productivity.** `bun erp make:feature`, `make:migration` and `make:seeder` emit a",
    "  fully wired, tested slice; the feature catalog installs whole modules.",
    "- **Two production targets.** VPS/Bun is the default (`APP_DEPLOY_TARGET=bun`). Cloudflare",
    "  (`APP_DEPLOY_TARGET=cloudflare`) sign-in fits Workers Free with the default PBKDF2 hash; Paid is",
    "  needed for `PASSWORD_HASH=scrypt` and heavier workloads. One Worker serves `/api` and `/api/*`;",
    "  static assets bypass Worker CPU. See Platform limits before adding runtime work.",
    GOAL_END,
  ].join("\n");
}

/** Platform limits body: portability rules for every target, Worker rules for Cloudflare only. */
export function renderPlatformBlock(): string {
  return [
    PLATFORM_START,
    "- **Every target:** no module-level mutable state as a source of truth. Per-process caches are TTL",
    "  optimisations; the database is authoritative, so a replica or isolate is correct without another's",
    "  memory.",
    "- **Every target, queries:** each route has a SQL statement budget in `http/query-budget.ts`; add one when you add a route. `bun erp test --filter http/query-budget` fails over budget and prints the statements.",
    "- **VPS/Bun (default):** no Worker CPU or bundle limit applies; the Bun API is available.",
    "- **When `APP_DEPLOY_TARGET=cloudflare`:** `check:worker` fails on unguarded Bun globals and on",
    "  migration/seed modules reachable from the Worker entry; migrations run outside the Worker. Keep",
    "  browser PDF rendering out of the Worker graph.",
    "- **When `APP_DEPLOY_TARGET=cloudflare`, CPU:** Workers Free allows 10 ms CPU per invocation and",
    "  sign-in hashes with PBKDF2 (`PASSWORD_HASH=pbkdf2`, default, ~2-4 ms) and fits Free; `scrypt` is",
    "  ~110 ms and needs Workers Paid (preflight enforces `cpu_ms`) (docs/deployment.md).",
    PLATFORM_END,
  ].join("\n");
}

/** Rewrites the generated blocks in AGENTS.md only when their content changed. */
export async function refreshGuidelines(root: string): Promise<GuidelinesStatus> {
  const path = resolve(root, AGENTS_FILE);
  // A container build copies only what it needs; no AGENTS.md means nothing to refresh.
  if (!(await Bun.file(path).exists())) return "missing";
  const source = await Bun.file(path).text();
  const applied = applyGuidelinesBlock(source, await renderGuidelinesBlock(root));
  if (applied.status === "missing") return "missing";
  let text = applied.source;
  const goal = applyGuidelinesBlock(text, renderGoalBlock(), { start: GOAL_START, end: GOAL_END });
  text = goal.source;
  const platform = applyGuidelinesBlock(text, renderPlatformBlock(), { start: PLATFORM_START, end: PLATFORM_END });
  text = platform.source;
  if (text === source) return "unchanged";
  await Bun.write(path, text);
  return "updated";
}
