import { resolve } from "node:path";
import { installedFeatureNames } from "./feature-catalog.ts";
import { installedPackageNames } from "./package-catalog.ts";

/**
 * Guidelines aggregation for agents. The block in AGENTS.md is generated, never hand-edited:
 * `features:install`, `packages:install` and `ai:update` refresh it from the installed catalog,
 * so the guide paths stay correct without anyone maintaining a second list.
 */

export const GUIDELINES_START = "<!-- guidelines:start -->";
export const GUIDELINES_END = "<!-- guidelines:end -->";
export const AGENTS_FILE = "AGENTS.md";

export type GuidelinesStatus = "updated" | "unchanged" | "missing";

/** Replaces the marked block in place; a source without both markers is left untouched. */
export function applyGuidelinesBlock(source: string, block: string): { source: string; status: GuidelinesStatus } {
  const start = source.indexOf(GUIDELINES_START);
  const end = source.indexOf(GUIDELINES_END);
  if (start < 0 || end < start) return { source, status: "missing" };
  const replaced = `${source.slice(0, start)}${block}${source.slice(end + GUIDELINES_END.length)}`;
  return { source: replaced, status: replaced === source ? "unchanged" : "updated" };
}

async function installedAppEntries(root: string): Promise<string[]> {
  let names: string[];
  try {
    names = [...new Bun.Glob("*/package.json").scanSync({ cwd: resolve(root, "apps") })]
      .map((file) => file.split("/")[0])
      .filter((name): name is string => Boolean(name))
      .sort();
  } catch {
    // `apps/` ships empty; a missing directory means no apps, not an error.
    return [];
  }
  const entries: string[] = [];
  for (const name of names) {
    const manifest = (await Bun.file(resolve(root, "apps", name, "package.json")).json()) as { name?: string };
    const appReadme = `apps/${name}/README.md`;
    const guide = (await Bun.file(resolve(root, appReadme)).exists()) ? appReadme : "templates/apps/README.md";
    entries.push(`\`${name}\` (\`${manifest.name ?? name}\`) — guide: \`${guide}\``);
  }
  return entries;
}

async function featureEntries(root: string): Promise<string[]> {
  const names = await installedFeatureNames(root);
  const entries: string[] = [];
  for (const name of names) {
    const readme = `templates/features/${name}/README.md`;
    const guide = (await Bun.file(resolve(root, readme)).exists()) ? readme : "templates/features/README.md";
    entries.push(`\`${name}\` — guide: \`${guide}\``);
  }
  return entries;
}

/** Deterministic, sorted, and small: one line per catalog area, guide paths included. */
export async function renderGuidelinesBlock(root: string): Promise<string> {
  const apps = await installedAppEntries(root);
  const packages = installedPackageNames(root).map((name) => `\`${name}\` (\`packages/${name}/llms.txt\`)`);
  const features = await featureEntries(root);
  const lines = [
    GUIDELINES_START,
    "Generated by `bun erp ai:update`; refresh it after installing apps, packages or features.",
    apps.length > 0
      ? `- Apps: ${apps.join("; ")}`
      : "- Apps: none installed — catalog guide: `templates/apps/README.md`",
    packages.length > 0
      ? `- Packages: ${packages.join("; ")}`
      : "- Packages: none installed — catalog: `templates/packages`",
    features.length > 0
      ? `- Features: ${features.join("; ")}`
      : "- Features: none installed — catalog guide: `templates/features/README.md`",
    GUIDELINES_END,
  ];
  return lines.join("\n");
}

/** Rewrites the block in AGENTS.md only when its content changed. */
export async function refreshGuidelines(root: string): Promise<GuidelinesStatus> {
  const path = resolve(root, AGENTS_FILE);
  const source = await Bun.file(path).text();
  const applied = applyGuidelinesBlock(source, await renderGuidelinesBlock(root));
  if (applied.status === "updated") await Bun.write(path, applied.source);
  return applied.status;
}
